release 2.6

diff --git a/tests/valgrind_suppressions.sh.in b/tests/valgrind_suppressions.sh.in
--- a/tests/valgrind_suppressions.sh.in
+++ b/tests/valgrind_suppressions.sh.in
@@ -1,8 +1,7 @@
 #! @SHELL@
 # --------------------------------------------------------------------- #
 #
-#  Script to run some examples through VALGRIND and
-#  to suppress errors
+#  Script to run an example through VALGRIND and generate suppressions
 #
 #  Michael Hagemann <michael.hagemann@unibas.ch>
 #
@@ -11,8 +10,17 @@
 # --------------------------------------------------------------------- #
 
 
+# Hack to run valgrind with new glibcs.  Problem: new TLS (thread
+# local storage)
+
+#VG_ENV="LD_ASSUME_KERNEL=2.2.5"
+
+# --num-callers=20 --leak-check=yes --leak-resolution=high --show-reachable=yes --suppressions=./suppressions.supp
+# --num-callers=20 --leak-resolution=high  --suppressions=/home/bettini/work/src2tags/tests/suppressions.supp
+
 VG_PRG="@VALGRIND@"
 VG_ARGS="--tool=memcheck --num-callers=20 --leak-check=yes --leak-resolution=high --show-reachable=yes --suppressions=@srcdir@/suppressions.supp --gen-suppressions=yes"
+#VG_ARGS="--tool=memcheck --num-callers=20 --leak-check=yes --leak-resolution=high --suppressions=@srcdir@/suppressions.supp"
 
 VGRIND="${VG_ENV} ${VG_PRG} ${VG_ARGS}"
 
@@ -32,7 +40,7 @@ ERROR=0
 
 vgrind () {
     if test ! -x "$1" -o "$1" == `basename $0`; then
-	# echo "Skipping $1."
+	echo "Skipping $1."
 	return
     fi
 
@@ -45,14 +53,43 @@ vgrind () {
         eval ${VGRIND} $*
     fi;
 
+    #grep -e "LEAK SUMMARY" ${TMP_LOG} >/dev/null 2>&1
+    grep -E "(reachable|lost): [1-9][0-9]*" ${TMP_LOG} >/dev/null 2>&1
+    if test "$?" == "0"; then
+	echo -n " LEAKS!"
+	
+	echo ""              >> ${SUMMARY}
+	echo "** $*, LEAKS"  >> ${SUMMARY}
+	cat ${TMP_LOG}       >> ${SUMMARY}
+	tmp_err=1
+    fi
+
+    grep -e "[1-9][0-9]* error" ${TMP_LOG} >/dev/null 2>&1
+    if test "$?" == "0"; then
+	echo -n " ERRORS!"
+
+	echo ""              >> ${SUMMARY}
+	echo "** $*, ERRORS" >> ${SUMMARY}
+	cat ${TMP_LOG}       >> ${SUMMARY}
+	tmp_err=1
+    fi
+
+    if test "x${tmp_err}" == "x"; then
+	echo " OK."
+    else
+	ERROR=1
+	echo ""
+    fi
+
+    rm -f ${TMP_LOG}
 }
 
 
 # --------------------------------------------------------------------- #
 
-for PROG in $*; do
-        vgrind @top_builddir@/tests/$PROG; 
-done
+echo "Run at ${DATE}" >${SUMMARY}
+
+vgrind $*
 
 
 # --------------------------------------------------------------------- #
